name: Build and deploy ASP.Net Core app to VPS - Vstore

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create .env file from secrets
        run: echo "${{ secrets.ENV_PRODUCTION }}" > .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile  # Path to Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_TAG }}/vstore:latest

  build-and-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-and-push  # Ensure this job runs after build-and-push
    steps:
      - name: Setup code
        uses: actions/checkout@v4

      - name: Build and deploy using Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 157.66.218.185  # Địa chỉ IP của server
          username: panhvuu04  # Tên người dùng SSH
          password: ${{ secrets.SSH_PASSWORD }}  # Mật khẩu SSH
          script: |
            # Di chuyển đến thư mục chứa project (có thể thay đổi theo project của bạn)
            cd /home/panhvuu04/VStore/
            
            # Tạo file .env từ secret ENV_PRODUCTION
            echo "${{ secrets.ENV_PRODUCTION }}" > .env
            
            # Pull the latest image from Docker Hub
            docker pull ${{ secrets.DOCKER_TAG }}/vstore:latest
            
            # Build và khởi động Docker Compose
            docker-compose down
            docker-compose build
            docker-compose up -d --force-recreate --remove-orphans